version: "3"

services:
  app:
    build: .
    container_name: github-profile-trophy
    restart: unless-stopped
    environment:
      ENABLE_REDIS: ${ENABLE_REDIS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      GITHUB_API: ${GITHUB_API}
      PORT: ${PORT}
      GITHUB_TOKEN1: ${GITHUB_TOKEN1}
      GITHUB_TOKEN2: ${GITHUB_TOKEN2}
    depends_on:
      - redis
    ports:
      - "4200:8080"

  redis:
    image: redis:latest
    container_name: trophy-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    expose:
      - "6379"

volumes:
  redis-data:
